apiVersion: 1

contactPoints:
  - orgId: 1
    name: incident-response
    receivers:
      - uid: incident-response-webhook
        type: webhook
        settings:
          url: http://incident-response:8001/alerts
          httpMethod: POST

policies:
  - orgId: 1
    receiver: incident-response
    group_by: [alertname, http_route]
    group_wait: 5s
    repeat_interval: 4h
